In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr
# On whihc index, the word will be 1

[[1878, 454, 2491, 2009],
 [1878, 454, 2491, 2931],
 [1878, 4540, 2491, 6397],
 [4596, 6806, 8504, 7264, 819],
 [4596, 6806, 8504, 7264, 7553],
 [6068, 1878, 9594, 2491, 4611],
 [3820, 8759, 1178, 7264]]

In [7]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding

# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1878  454 2491 2009]
 [   0    0    0    0 1878  454 2491 2931]
 [   0    0    0    0 1878 4540 2491 6397]
 [   0    0    0 4596 6806 8504 7264  819]
 [   0    0    0 4596 6806 8504 7264 7553]
 [   0    0    0 6068 1878 9594 2491 4611]
 [   0    0    0    0 3820 8759 1178 7264]]


In [10]:
## feature representation
dim=10

In [16]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.build((None, sent_length))  # Manually build the model specifying the input shape
model.compile('adam', 'mse')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[[-0.04262124,  0.02216533, -0.01957545, -0.00324422,
          0.02878294,  0.01914493, -0.03090218,  0.00813895,
          0.00095217, -0.02563443],
        [-0.04262124,  0.02216533, -0.01957545, -0.00324422,
          0.02878294,  0.01914493, -0.03090218,  0.00813895,
          0.00095217, -0.02563443],
        [-0.04262124,  0.02216533, -0.01957545, -0.00324422,
          0.02878294,  0.01914493, -0.03090218,  0.00813895,
          0.00095217, -0.02563443],
        [-0.04262124,  0.02216533, -0.01957545, -0.00324422,
          0.02878294,  0.01914493, -0.03090218,  0.00813895,
          0.00095217, -0.02563443],
        [-0.01654072, -0.04757398, -0.0331413 ,  0.01817271,
         -0.0048602 , -0.02213562, -0.037202  , -0.0310388 ,
         -0.03934059, -0.04714165],
        [ 0.02976319, -0.04038526, -0.03203799, -0.00020441,
          0.01048647,  0.01728928, -0.03245051, -0.00574733,
          0.00544338,  0.02438741],
        [ 0.03772268, -0.01716502, -0.00432063, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 1878,  454, 2491, 2009])

In [19]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None